services:
  webapi1:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "8080"

  webapi2:
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - webapi1
      - webapi2
